VER2
REM Список элементов
REM IBS@57_DEV
REM Версия ТЯ: 7.3.4.0
REM Версия Администратора проектов: 6.93.0.41

TYPE ADE_PART4TST   'ОАЭ. Разделение. Тест
ATTR ADE_PART4TST DATE_CR
ATTR ADE_PART4TST VAL
ATTR ADE_PART4TST X
ATTR ADE_PART4TST Y
CRIT ADE_PART4TST VW_CRIT_ADE_PART4TST
IDX ADE_PART4TST IDX_Z#ADE_PART4TST_DATE_CR
METH ADE_PART4TST ADD_DATA
METH ADE_PART4TST DELETE_AUTO
METH ADE_PART4TST EDIT_AUTO
METH ADE_PART4TST NEW_AUTO
